#!/usr/bin/env python
#Menu for MMAP
#Author: @nahberry

import sys
sys.path.append("/users/nate/appdata/local/programs/python/python39/lib/site-packages")
import colorama
from colorama import init
from colorama import Fore

init()

def mainMenu():

    print( Fore.WHITE +

    """
1. Common scans
2. Favorites
3. NSE Scripts
4. Exit

"""
    )

def commonScans():

    print( Fore.YELLOW +

    """

               ....
         .................
      .......................
    ..........................
   .............................
  ...............................
 .................................
 .................................
................................
..............................
...........................        ....    ....    ....
.........................          ....    ....    ....
.......................            ....    ....    ....
..........................
..............................
 ................................
 ..................................
  .................................
   ...............................
    .............................
      .........................
       ......................
            ...............
                ......

"""
)

    print( Fore.WHITE +

    """

1. Basic TCP Scan
2. SYN Scan (Stealth)
3. UDP Scan
4. Detect OS and Services
5. Standard Service Detection
6. Scan from List
7. Scan Single Port
8. Scan All Ports
9. Back to Main Menu


    """

    )
